// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_primes_RCPPEXPORTS_H_GEN_
#define RCPP_primes_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace primes {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("primes", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("primes", "_primes_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in primes");
            }
        }
    }

    inline int gcd_(int m, int n) {
        typedef SEXP(*Ptr_gcd_)(SEXP,SEXP);
        static Ptr_gcd_ p_gcd_ = NULL;
        if (p_gcd_ == NULL) {
            validateSignature("int(*gcd_)(int,int)");
            p_gcd_ = (Ptr_gcd_)R_GetCCallable("primes", "_primes_gcd_");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_gcd_(Shield<SEXP>(Rcpp::wrap(m)), Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline int Rgcd_(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_Rgcd_)(SEXP);
        static Ptr_Rgcd_ p_Rgcd_ = NULL;
        if (p_Rgcd_ == NULL) {
            validateSignature("int(*Rgcd_)(const Rcpp::IntegerVector&)");
            p_Rgcd_ = (Ptr_Rgcd_)R_GetCCallable("primes", "_primes_Rgcd_");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Rgcd_(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline int scm_(int m, int n) {
        typedef SEXP(*Ptr_scm_)(SEXP,SEXP);
        static Ptr_scm_ p_scm_ = NULL;
        if (p_scm_ == NULL) {
            validateSignature("int(*scm_)(int,int)");
            p_scm_ = (Ptr_scm_)R_GetCCallable("primes", "_primes_scm_");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_scm_(Shield<SEXP>(Rcpp::wrap(m)), Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline int Rscm_(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_Rscm_)(SEXP);
        static Ptr_Rscm_ p_Rscm_ = NULL;
        if (p_Rscm_ == NULL) {
            validateSignature("int(*Rscm_)(const Rcpp::IntegerVector&)");
            p_Rscm_ = (Ptr_Rscm_)R_GetCCallable("primes", "_primes_Rscm_");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Rscm_(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline Rcpp::IntegerVector gcd_impl(const Rcpp::IntegerVector& m, const Rcpp::IntegerVector& n) {
        typedef SEXP(*Ptr_gcd_impl)(SEXP,SEXP);
        static Ptr_gcd_impl p_gcd_impl = NULL;
        if (p_gcd_impl == NULL) {
            validateSignature("Rcpp::IntegerVector(*gcd_impl)(const Rcpp::IntegerVector&,const Rcpp::IntegerVector&)");
            p_gcd_impl = (Ptr_gcd_impl)R_GetCCallable("primes", "_primes_gcd_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_gcd_impl(Shield<SEXP>(Rcpp::wrap(m)), Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::IntegerVector >(rcpp_result_gen);
    }

    inline Rcpp::IntegerVector scm_impl(const Rcpp::IntegerVector& m, const Rcpp::IntegerVector& n) {
        typedef SEXP(*Ptr_scm_impl)(SEXP,SEXP);
        static Ptr_scm_impl p_scm_impl = NULL;
        if (p_scm_impl == NULL) {
            validateSignature("Rcpp::IntegerVector(*scm_impl)(const Rcpp::IntegerVector&,const Rcpp::IntegerVector&)");
            p_scm_impl = (Ptr_scm_impl)R_GetCCallable("primes", "_primes_scm_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_scm_impl(Shield<SEXP>(Rcpp::wrap(m)), Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::IntegerVector >(rcpp_result_gen);
    }

    inline Rcpp::LogicalVector coprime_impl(const Rcpp::IntegerVector& m, const Rcpp::IntegerVector& n) {
        typedef SEXP(*Ptr_coprime_impl)(SEXP,SEXP);
        static Ptr_coprime_impl p_coprime_impl = NULL;
        if (p_coprime_impl == NULL) {
            validateSignature("Rcpp::LogicalVector(*coprime_impl)(const Rcpp::IntegerVector&,const Rcpp::IntegerVector&)");
            p_coprime_impl = (Ptr_coprime_impl)R_GetCCallable("primes", "_primes_coprime_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_coprime_impl(Shield<SEXP>(Rcpp::wrap(m)), Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::LogicalVector >(rcpp_result_gen);
    }

    inline std::vector<int> generate_n_primes_impl(int n) {
        typedef SEXP(*Ptr_generate_n_primes_impl)(SEXP);
        static Ptr_generate_n_primes_impl p_generate_n_primes_impl = NULL;
        if (p_generate_n_primes_impl == NULL) {
            validateSignature("std::vector<int>(*generate_n_primes_impl)(int)");
            p_generate_n_primes_impl = (Ptr_generate_n_primes_impl)R_GetCCallable("primes", "_primes_generate_n_primes_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_generate_n_primes_impl(Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<std::vector<int> >(rcpp_result_gen);
    }

    inline Rcpp::LogicalVector is_prime_impl(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_is_prime_impl)(SEXP);
        static Ptr_is_prime_impl p_is_prime_impl = NULL;
        if (p_is_prime_impl == NULL) {
            validateSignature("Rcpp::LogicalVector(*is_prime_impl)(const Rcpp::IntegerVector&)");
            p_is_prime_impl = (Ptr_is_prime_impl)R_GetCCallable("primes", "_primes_is_prime_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_is_prime_impl(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::LogicalVector >(rcpp_result_gen);
    }

    inline Rcpp::List k_tuple_impl(int min, int max, std::vector<int> tuple) {
        typedef SEXP(*Ptr_k_tuple_impl)(SEXP,SEXP,SEXP);
        static Ptr_k_tuple_impl p_k_tuple_impl = NULL;
        if (p_k_tuple_impl == NULL) {
            validateSignature("Rcpp::List(*k_tuple_impl)(int,int,std::vector<int>)");
            p_k_tuple_impl = (Ptr_k_tuple_impl)R_GetCCallable("primes", "_primes_k_tuple_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_k_tuple_impl(Shield<SEXP>(Rcpp::wrap(min)), Shield<SEXP>(Rcpp::wrap(max)), Shield<SEXP>(Rcpp::wrap(tuple)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline Rcpp::List sexy_prime_triplets_impl(int min, int max) {
        typedef SEXP(*Ptr_sexy_prime_triplets_impl)(SEXP,SEXP);
        static Ptr_sexy_prime_triplets_impl p_sexy_prime_triplets_impl = NULL;
        if (p_sexy_prime_triplets_impl == NULL) {
            validateSignature("Rcpp::List(*sexy_prime_triplets_impl)(int,int)");
            p_sexy_prime_triplets_impl = (Ptr_sexy_prime_triplets_impl)R_GetCCallable("primes", "_primes_sexy_prime_triplets_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sexy_prime_triplets_impl(Shield<SEXP>(Rcpp::wrap(min)), Shield<SEXP>(Rcpp::wrap(max)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline Rcpp::IntegerVector next_prime_impl(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_next_prime_impl)(SEXP);
        static Ptr_next_prime_impl p_next_prime_impl = NULL;
        if (p_next_prime_impl == NULL) {
            validateSignature("Rcpp::IntegerVector(*next_prime_impl)(const Rcpp::IntegerVector&)");
            p_next_prime_impl = (Ptr_next_prime_impl)R_GetCCallable("primes", "_primes_next_prime_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_next_prime_impl(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::IntegerVector >(rcpp_result_gen);
    }

    inline Rcpp::IntegerVector prev_prime_impl(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_prev_prime_impl)(SEXP);
        static Ptr_prev_prime_impl p_prev_prime_impl = NULL;
        if (p_prev_prime_impl == NULL) {
            validateSignature("Rcpp::IntegerVector(*prev_prime_impl)(const Rcpp::IntegerVector&)");
            p_prev_prime_impl = (Ptr_prev_prime_impl)R_GetCCallable("primes", "_primes_prev_prime_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_prev_prime_impl(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::IntegerVector >(rcpp_result_gen);
    }

    inline Rcpp::IntegerVector nth_prime_impl(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_nth_prime_impl)(SEXP);
        static Ptr_nth_prime_impl p_nth_prime_impl = NULL;
        if (p_nth_prime_impl == NULL) {
            validateSignature("Rcpp::IntegerVector(*nth_prime_impl)(const Rcpp::IntegerVector&)");
            p_nth_prime_impl = (Ptr_nth_prime_impl)R_GetCCallable("primes", "_primes_nth_prime_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_nth_prime_impl(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::IntegerVector >(rcpp_result_gen);
    }

    inline int prime_count_impl(int n, bool upper_bound) {
        typedef SEXP(*Ptr_prime_count_impl)(SEXP,SEXP);
        static Ptr_prime_count_impl p_prime_count_impl = NULL;
        if (p_prime_count_impl == NULL) {
            validateSignature("int(*prime_count_impl)(int,bool)");
            p_prime_count_impl = (Ptr_prime_count_impl)R_GetCCallable("primes", "_primes_prime_count_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_prime_count_impl(Shield<SEXP>(Rcpp::wrap(n)), Shield<SEXP>(Rcpp::wrap(upper_bound)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline int nth_prime_estimate_impl(int n, bool upper_bound) {
        typedef SEXP(*Ptr_nth_prime_estimate_impl)(SEXP,SEXP);
        static Ptr_nth_prime_estimate_impl p_nth_prime_estimate_impl = NULL;
        if (p_nth_prime_estimate_impl == NULL) {
            validateSignature("int(*nth_prime_estimate_impl)(int,bool)");
            p_nth_prime_estimate_impl = (Ptr_nth_prime_estimate_impl)R_GetCCallable("primes", "_primes_nth_prime_estimate_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_nth_prime_estimate_impl(Shield<SEXP>(Rcpp::wrap(n)), Shield<SEXP>(Rcpp::wrap(upper_bound)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline Rcpp::List prime_factors_impl(const Rcpp::IntegerVector& x) {
        typedef SEXP(*Ptr_prime_factors_impl)(SEXP);
        static Ptr_prime_factors_impl p_prime_factors_impl = NULL;
        if (p_prime_factors_impl == NULL) {
            validateSignature("Rcpp::List(*prime_factors_impl)(const Rcpp::IntegerVector&)");
            p_prime_factors_impl = (Ptr_prime_factors_impl)R_GetCCallable("primes", "_primes_prime_factors_impl");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_prime_factors_impl(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline std::vector<int> generate_primes_(int min, int max) {
        typedef SEXP(*Ptr_generate_primes_)(SEXP,SEXP);
        static Ptr_generate_primes_ p_generate_primes_ = NULL;
        if (p_generate_primes_ == NULL) {
            validateSignature("std::vector<int>(*generate_primes_)(int,int)");
            p_generate_primes_ = (Ptr_generate_primes_)R_GetCCallable("primes", "_primes_generate_primes_");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_generate_primes_(Shield<SEXP>(Rcpp::wrap(min)), Shield<SEXP>(Rcpp::wrap(max)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<std::vector<int> >(rcpp_result_gen);
    }

}

#endif // RCPP_primes_RCPPEXPORTS_H_GEN_
