# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gcd_ <- function(m, n) {
    .Call('_primes_gcd_', PACKAGE = 'primes', m, n)
}

Rgcd_ <- function(x) {
    .Call('_primes_Rgcd_', PACKAGE = 'primes', x)
}

scm_ <- function(m, n) {
    .Call('_primes_scm_', PACKAGE = 'primes', m, n)
}

Rscm_ <- function(x) {
    .Call('_primes_Rscm_', PACKAGE = 'primes', x)
}

gcd_impl <- function(m, n) {
    .Call('_primes_gcd_impl', PACKAGE = 'primes', m, n)
}

scm_impl <- function(m, n) {
    .Call('_primes_scm_impl', PACKAGE = 'primes', m, n)
}

coprime_impl <- function(m, n) {
    .Call('_primes_coprime_impl', PACKAGE = 'primes', m, n)
}

generate_n_primes_impl <- function(n) {
    .Call('_primes_generate_n_primes_impl', PACKAGE = 'primes', n)
}

is_prime_impl <- function(x) {
    .Call('_primes_is_prime_impl', PACKAGE = 'primes', x)
}

k_tuple_impl <- function(min, max, tuple) {
    .Call('_primes_k_tuple_impl', PACKAGE = 'primes', min, max, tuple)
}

sexy_prime_triplets_impl <- function(min, max) {
    .Call('_primes_sexy_prime_triplets_impl', PACKAGE = 'primes', min, max)
}

next_prime_impl <- function(x) {
    .Call('_primes_next_prime_impl', PACKAGE = 'primes', x)
}

prev_prime_impl <- function(x) {
    .Call('_primes_prev_prime_impl', PACKAGE = 'primes', x)
}

nth_prime_impl <- function(x) {
    .Call('_primes_nth_prime_impl', PACKAGE = 'primes', x)
}

prime_count_impl <- function(n, upper_bound) {
    .Call('_primes_prime_count_impl', PACKAGE = 'primes', n, upper_bound)
}

nth_prime_estimate_impl <- function(n, upper_bound) {
    .Call('_primes_nth_prime_estimate_impl', PACKAGE = 'primes', n, upper_bound)
}

prime_factors_impl <- function(x) {
    .Call('_primes_prime_factors_impl', PACKAGE = 'primes', x)
}

generate_primes_ <- function(min, max) {
    .Call('_primes_generate_primes_', PACKAGE = 'primes', min, max)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_primes_RcppExport_registerCCallable', PACKAGE = 'primes')
})
