# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gcd_ <- function(m, n) {
    .Call('_primes_gcd_', PACKAGE = 'primes', m, n)
}

Rgcd_ <- function(x) {
    .Call('_primes_Rgcd_', PACKAGE = 'primes', x)
}

scm_ <- function(m, n) {
    .Call('_primes_scm_', PACKAGE = 'primes', m, n)
}

Rscm_ <- function(x) {
    .Call('_primes_Rscm_', PACKAGE = 'primes', x)
}

gcd <- function(m, n) {
    .Call('_primes_gcd', PACKAGE = 'primes', m, n)
}

scm <- function(m, n) {
    .Call('_primes_scm', PACKAGE = 'primes', m, n)
}

coprime <- function(m, n) {
    .Call('_primes_coprime', PACKAGE = 'primes', m, n)
}

generate_n_primes <- function(n) {
    .Call('_primes_generate_n_primes', PACKAGE = 'primes', n)
}

is_prime <- function(x) {
    .Call('_primes_is_prime', PACKAGE = 'primes', x)
}

k_tuple <- function(min, max, tuple) {
    .Call('_primes_k_tuple', PACKAGE = 'primes', min, max, tuple)
}

sexy_prime_triplets <- function(min, max) {
    .Call('_primes_sexy_prime_triplets', PACKAGE = 'primes', min, max)
}

next_prime <- function(x) {
    .Call('_primes_next_prime', PACKAGE = 'primes', x)
}

prev_prime <- function(x) {
    .Call('_primes_prev_prime', PACKAGE = 'primes', x)
}

nth_prime <- function(x) {
    .Call('_primes_nth_prime', PACKAGE = 'primes', x)
}

prime_count <- function(n, upper_bound) {
    .Call('_primes_prime_count', PACKAGE = 'primes', n, upper_bound)
}

nth_prime_estimate <- function(n, upper_bound) {
    .Call('_primes_nth_prime_estimate', PACKAGE = 'primes', n, upper_bound)
}

prime_factors <- function(x) {
    .Call('_primes_prime_factors', PACKAGE = 'primes', x)
}

generate_primes_ <- function(min, max) {
    .Call('_primes_generate_primes_', PACKAGE = 'primes', min, max)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_primes_RcppExport_registerCCallable', PACKAGE = 'primes')
})
